### ISSUE TITLE
Evaluate changes to projects needed to support the new proxy submitter model 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#12]
Evaluate which projects need to be updated based on model changes, and create issues to deal with them. (e.g. NIHMS submission ETL may need changes to algorithm).  Note: some things will change purely to support data model changes, not because their functionality is to do with proxy user functionality. Things like changed field names, default values etc. Those are the sorts of things this will aim to identify.

Expected outcomes include draft cards for each components. Each component lead will need to work with you on the part that is relevant to their components.

RET 1 days <-- i think this is going to take more than 1 day

**Comment by karenhanson** [comment]
The following issues were generated as a result of this:

https://github.com/OA-PASS/general-issues/issues/18
https://github.com/OA-PASS/nihms-submission-etl/issues/21
https://github.com/OA-PASS/pass-grant-loader/issues/23
https://github.com/OA-PASS/deposit-services/issues/150
https://github.com/OA-PASS/pass-docker/issues/120
https://github.com/OA-PASS/pass-docker/issues/121
https://github.com/OA-PASS/java-fedora-client/issues/50
https://github.com/OA-PASS/general-issues/issues/19
https://github.com/OA-PASS/general-issues/issues/13 (not new, added more info, need to revise time)

No new issues were added for `pass-ember`, `pass-authz`, or `notification-services` since the updates for those related to the data model are basically the work for proxy user!
