### ISSUE TITLE
Somehow submission prepared by a proxy gets a submission uri for its submitter email

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#142]
this is the case both BEFORE and AFTER a submisison was reviewed and approved by its submitter. 
This is faily visible on the UI. Needs to be fix, as soon as possible.

The correct behavior is, is the submitter is a user of the system this field should have `username` and `(useremail)`. If the submitter is not user in the system , then name and email provided when the proxy submission was initiated should be used. 

![Screen Shot 2020-06-09 at 12 04 54 PM](https://user-images.githubusercontent.com/11050142/84172145-a8d3aa80-aa49-11ea-857f-1c8e35038728.png)

**Comment by emetsger** [comment]
@jaredgalanis if you get started on this before me, I would verify that the Submission resource in Fedora has the expected content at each step in the overall workflow:
* after the Submission resource is created by pass-ember upon preparation
* after the Submission resource is submitted by pass-ember by the submitter

Isolating where things get messed up would help, or maybe ember is just interrogating the wrong field of the Submission when displaying the page; e.g. `submission.submission()` vs `submission.submitter()`

**Comment by emetsger** [comment]
Ok to date this issue is only replicable when you are preparing a submission for a User that is already in the system (i.e. you are searching for an existing user).  When performing a proxy submission using an email and a name, this issue is not seen.

When performing a non-proxy submission, this issue is not seen.

To observe the behavior, start pass docker.
Log in to PASS.
Perform step 1 of a new submission, preparing a submission on behalf of an existing User.
Obtain the submission ID.

After clicking next to advance to step 2 of the workflow, load the submission resource in your browser from Fedora.  Note that submitterEmail points to the Submission resource.

This issue can be replicated with a minimum of system components running in pass-docker, so it does not appear to be a rouge interaction with a back-end service like DS, NS, or authz.

Looking at the wire capture from the fedora container's perspective, the POST for creating the new submission comes in with the correct content (submitterEmail is the empty string).  Because all the other backend containers are stopped, there are no modifications performed to any resources, to the submission or its acls.

The response to the first GET of the submission by fedora shows the _incorrect_ content: submitterEmail has a value equal to the submission URI.

So this is happening within Fedora, it seems, rather than on the wire.

Minimum containers necessary to advance to step 2 of performing a proxy submission.
```
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS                                                                        NAMES
0d84955a41b3        oapass/fcrepo:4.7.5-3.4-2                                 "/bin/entrypoint.sh"     6 hours ago         Up 6 minutes        0.0.0.0:5006->5006/tcp, 0.0.0.0:8080->8080/tcp                               fcrepo
d29b96f9142d        oapass/idp:20190813-jhu                                   "run-jetty.sh"           6 hours ago         Up 6 hours          4443/tcp, 8443/tcp                                                           idp
d70723e19f10        oapass/sp:20200507                                        "httpd-shibd-foregro…"   6 hours ago         Up 9 minutes        80/tcp, 443/tcp                                                              sp
819a9ca08402        oapass/activemq:20200219                                  "/bin/sh -c /usr/loc…"   6 hours ago         Up 6 hours          0.0.0.0:8161->8161/tcp, 0.0.0.0:61613->61613/tcp, 0.0.0.0:61616->61616/tcp   activemq
e73b4c00e96a        oapass/httpd-proxy:20200507                               "httpd-foreground.sh"    6 hours ago         Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                     proxy
8d0a1dc7ad50        oapass/static-html:jhu-20200518-451907e                   "/bin/entrypoint.sh"     6 hours ago         Up 8 minutes        80/tcp, 0.0.0.0:82->82/tcp                                                   static-html
da7497f7fea0        oapass/ldap:20200610-jhu                                  "/bin/sh -c '/usr/sb…"   6 hours ago         Up 6 hours          389/tcp                                                                      ldap
0453d306ce88        oapass/doi-service:version1.0.0                           "catalina.sh run"        6 hours ago         Up 6 hours          0.0.0.0:8090->8080/tcp                                                       doiservice
3723da03d0cb        oapass/ember:20200521-172a2948                            "/bin/entrypoint.sh"     6 hours ago         Up 6 hours          80/tcp                                                                       ember
52ddeb3a196d        docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3   "/usr/local/bin/dock…"   6 hours ago         Up 7 minutes        0.0.0.0:9200->9200/tcp, 9300/tcp                                             elasticsearch
```

All of these containers are required to start the UI and perform a submission.

**Comment by emetsger** [comment]
I amend my previous comment- here are the conditions necessary to replicate this issue:

Log in to PASS.
Load the page for performing step 1 of the submission.
Do not click on anything (especially the modal dialog for preparing a submission), except to provide a DOI.
Click next.
Obtain the Submission ID and load the submission in the browser.  Observe the submission is as expected; no submission URI for the submitter email.

Start a new submission.
Perform exactly: click the "Someone else" radio button, then click the "Myself" radio button
Provide a DOI.
Click next.
Obtain the submission ID and view the submission in the browser.  Observe that the submission has the submission URI as the submitter email.

**Comment by emetsger** [comment]
When the modal interaction occurs, ember is sending a submitterEmail and submitterName as empty strings.  When there is no modal interaction, ember sends submitterEmail and submitterName as null.

**Comment by emetsger** [comment]
POSTing 
this (`submitterEmail` with an empty string):

```json
{
  “@context”: “https://oa-pass.github.io/pass-data-model/src/main/resources/context-3.4.jsonld”,
  “@id”: “”,
  “@type”: “Submission”,
  “aggregatedDepositStatus”: “not-started”,
  “submittedDate”: null,
  “source”: “pass”,
  “metadata”: null,
  “submitted”: false,
  “submissionStatus”: “draft”,
  “submitterName”: “”,
  “submitterEmail”: “”,
  “submitter”: “https://pass.local/fcrepo/rest/users/21/36/86/ff/213686ff-da91-455b-977d-b1bae238d9b6”,
  “preparers”: [
    “https://pass.local/fcrepo/rest/users/0f/46/19/45/0f461945-d381-460e-9cc1-be4b246faa95”
  ],
  “publication”: null,
  “repositories”: null,
  “effectivePolicies”: null,
  “grants”: null
}
```


Results in:

```json
{
  “@id” : “https://pass.local/fcrepo/rest/submissions/15/3f/09/75/153f0975-b94d-4293-ad9a-df4cc1a2f59b”,
  “@type” : “Submission”,
  “aggregatedDepositStatus” : “not-started”,
  “preparers” : [ “https://pass.local/fcrepo/rest/users/0f/46/19/45/0f461945-d381-460e-9cc1-be4b246faa95” ],
  “source” : “pass”,
  “submissionStatus” : “draft”,
  “submitted” : false,
  “submitter” : “https://pass.local/fcrepo/rest/users/21/36/86/ff/213686ff-da91-455b-977d-b1bae238d9b6”,
  “submitterEmail” : “https://pass.local/fcrepo/rest/submissions/15/3f/09/75/153f0975-b94d-4293-ad9a-df4cc1a2f59b”,
  “submitterName” : “”,
  “@context” : “https://oa-pass.github.io/pass-data-model/src/main/resources/context-3.4.jsonld”
}
```

**Comment by emetsger** [comment]
So the issue is that `submitterEmail` is identified as an `@id` in the JSON LD context.  We can argue if that's correct or not, but when the JSON LD is processed, a resource (i.e. something typed as an `@id`, in this case the `submitterEmail`) with an empty identifier is interpreted correctly as "the identifier of the current resource".  That is `""` in json ld is the equivalent of the `<>` empty resource uri in RDF.  And so the field is assigned the resource uri of the submission.

Ember will need to be careful to never submit a Submission with `submitterEmail` as the empty string.  Submitting that field as `null` will work.
