### ISSUE TITLE
Add Denis to relevant grants in demo instance

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#2]
Details to be filled out. 
 He's already in the system and has many grants. 

He'll need at least an NIH grant, a ED grant and an and USAID grant. The goal is that Denis will be able to  demo all possible workflow of PASS. 

grants doc from Karen https://docs.google.com/document/d/1B5qvMAuOJuZ4gAud9j3GAShizTUBoZEO05KJrnqlD7c/edit

**Comment by htpvu** [comment]
@birkland please inform Sayeed when Denis' account is ready to go.

**Comment by birkland** [comment]
As it turns out, he was affected by assigning some of his grants to others.  

A ED grant he is PI on was assigned to John:
https://pass.local/fcrepo/rest/grants/a9/c5/d6/4d/a9c5d64d-05ea-4776-ad8f-0881e45d9242

I changed it so that he retains PI on it, and John is a CO-PI.

I also added a USAID grant:
https://demo.pass.library.jhu.edu/fcrepo/rest/grants/73/0d/5b/f1/730d5bf1-2953-4c0b-b21b-1d7744e57bcc

No now his user has NIH, ED, and USAID
